### ISSUE TITLE
HAL support for multiple link objects per relationship?

### ISSUE THREAD

**Issue by abargnesi** [ismasan/oat#58]
I am trying to capture multiple `item` link objects in a HAL representation. Something like:

```json
{
  "person": {
    "name": "Oaty",
    "_links": {
      "item": [
        {
          "type": "address",
          "href": "/people/1/address/1"
        },
        {
          "type": "address",
          "href": "/people/1/address/2"
        }
      ]
    }
  }
}
```

The HAL adapter seems to need an `:href` key on the link hash (e.g. `opts[:href]`) to set the link object for the relationship ([lib/oat/adapters/hal.rb:6](https://github.com/ismasan/oat/blob/master/lib/oat/adapters/hal.rb#L6)).

Is there another way to set an array of link objects for a single relationship? HAL supports this ([spec reference](https://tools.ietf.org/html/draft-kelly-json-hal-06#section-4.1.1)).

**Comment by ismasan** [comment]
Hi.

Thanks for this. The current HAL implementation needs to be brought up to date with the current spec in order to cover this. Happy to accept pull requests for this specific feature.
