### ISSUE TITLE
Cross-cutting concerns

### ISSUE THREAD

**Issue by blevine** [ismasan/oat#61]
Hi,

I want to include pagination links in all collections. What's the best way to go about this? I don't think that creating a base CollectionSerializer class will work since 'schema' is a class method.  And I'm not sure how I would go about this using mixins or concerns.  Any advice?

**Comment by blevine** [comment]
Never mind.  Figured it out by reading the docs a bit more carefully.

**Comment by ismasan** [comment]
No worries, hope it worked!
