### ISSUE TITLE
JsonApi adapter generates anything but JSON API conformant document

### ISSUE THREAD

**Issue by szubtsovskiy** [ismasan/oat#62]
Hi guys,

I've tried to use Oat to generate JSON API response to consume by my JavaScript application and discovered that output does not even look similar to what is described here: http://jsonapi.org/format/#url-based-json-api. For example, there is no "data" section and no "included" section but there is "linked" section. JSON API does not even have such keyword...

I am really confused by this fact because it looked like Oat is what I really need and I did like the blog article where the motivation is described. However it looks like Oat does not suit my needs unless I write my own adapter (which is not hard, I understand it).

I would be really grateful if someone could explain me what's happening (or was happening) with Oat and JsonApi adapter. Was there another JSON API specification previously?

Thanks!

**Comment by ismasan** [comment]
Hello.

Unfortunately Oat's JsonAPI implementation is for an older version of the JsonAPI spec. Since I don't use JsonAPI myself I have no plans to update it, but I'd be happy to either accept pull requests or a new Oat-JsonAPI implementation as a separate gem.

**Comment by szubtsovskiy** [comment]
Thanks, that's what I thought. I will consider writing new adapter!
